version: '3'

services:
  terraform:
    command: $COMMAND
    image: hashicorp/terraform:$VERSION
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    volumes:
      - $DIR:/app
    working_dir: /app
