version: '3'

services:
  terragrunt:
    image: $DOCKER_IMAGE
    command: bash -c "$COMMAND"
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_REGION: $AWS_REGION
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      GITHUB_TOKEN: $GITHUB_TOKEN
      TERRAGRUNT_PARALLELISM: 16 # * Max parallel builds
      TF_INPUT: false # * Disable interactive prompts
    volumes:
      - $DIR:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
