name: CICD V0

on:
  push:
    branches:
      - main
    paths:
      - .github/**
      - infra/**
      - scripts/**
      - src/**

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code ...
        uses: actions/checkout@v3
      - name: Gaining permission to read and execute all files ...
        run: |
          find . \
            -not -path "*.github/**" \
            -not -path "*dist/*" \
            -not -path "*node_modules/*" \
            -not -path "*terraform*" \
            -type f \
            -exec chmod 544 {} +
      - name: Running ./scripts/terragrunt/cli ...
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CICD_V0_AWS_ACCESS_KEY_ID }}
          AWS_REGION: ${{ secrets.CICD_V0_AWS_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CICD_V0_AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.MANUAL_GITHUB_TOKEN }}
        run: ./scripts/terragrunt/cli run-all apply
